#!/usr/bin/env python3

import os
import collections

self_dir = os.path.dirname(__file__)
posts_dir = os.path.join(self_dir, '_posts')
tags_dir = os.path.join(self_dir, '_tags')
tags = collections.defaultdict(int)
for fn in os.listdir(posts_dir):
    sepcount = 0
    if fn.startswith('.'):
        continue
    for line in open(os.path.join(posts_dir, fn)).readlines():
        if line.strip() == '---':
            sepcount += 1
            if sepcount >= 2:
                break
        if line.startswith('tags: '):
            for tag in line.split(':', 1)[-1].split():
                if not tag:
                    continue
                tags[tag] += 1

for fn in os.listdir(tags_dir):
    if os.path.splitext(fn)[0] not in tags:
        os.unlink(os.path.join(tags_dir, fn))
        print(f"Removed {fn}")
for tag, count in sorted(tags.items()):
    with open(os.path.join(tags_dir, f"{tag}.md"), 'w') as f:
        f.write(f"---\nlayout: tag\npost_count: {count}\n---\n")
        print(f"{tag}.md ({count})")
